//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class ReferenceTitle {
    
    private string titleTextField;
    
    /// <remarks/>
    public string TitleText {
        get {
            return this.titleTextField;
        }
        set {
            this.titleTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class Title {
    
    private string titleTextField;
    
    private string titleTypeField;
    
    /// <remarks/>
    public string TitleText {
        get {
            return this.titleTextField;
        }
        set {
            this.titleTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string TitleType {
        get {
            return this.titleTypeField;
        }
        set {
            this.titleTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class DisplayArtist {
    
    private string artistRoleField;
    
    private PartyName[] partyNameField;
    
    private string sequenceNumberField;
    
    /// <remarks/>
    public string ArtistRole {
        get {
            return this.artistRoleField;
        }
        set {
            this.artistRoleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PartyName")]
    public PartyName[] PartyName {
        get {
            return this.partyNameField;
        }
        set {
            this.partyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class PartyName {
    
    private string fullNameField;
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class PLine {
    
    private string yearField;
    
    private string pLineTextField;
    
    /// <remarks/>
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public string PLineText {
        get {
            return this.pLineTextField;
        }
        set {
            this.pLineTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class Genre {
    
    private string genreTextField;
    
    private string subGenreField;
    
    /// <remarks/>
    public string GenreText {
        get {
            return this.genreTextField;
        }
        set {
            this.genreTextField = value;
        }
    }
    
    /// <remarks/>
    public string SubGenre {
        get {
            return this.subGenreField;
        }
        set {
            this.subGenreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class File {
    
    private string fileNameField;
    
    /// <remarks/>
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=true)]
public partial class ReleaseResourceReference {
    
    private string releaseResourceTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string ReleaseResourceType {
        get {
            return this.releaseResourceTypeField;
        }
        set {
            this.releaseResourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class ResourceGroup {
    
    private string sequenceNumberField;
    
    private ResourceGroupContentItem[] resourceGroupContentItemField;
    
    private Title[] titleField;
    
    /// <remarks/>
    public string SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResourceGroupContentItem")]
    public ResourceGroupContentItem[] ResourceGroupContentItem {
        get {
            return this.resourceGroupContentItemField;
        }
        set {
            this.resourceGroupContentItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Title")]
    public Title[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class ResourceGroupContentItem {
    
    private string sequenceNumberField;
    
    private string resourceTypeField;
    
    private ReleaseResourceReference[] releaseResourceReferenceField;
    
    /// <remarks/>
    public string SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ResourceType {
        get {
            return this.resourceTypeField;
        }
        set {
            this.resourceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReleaseResourceReference", IsNullable=true)]
    public ReleaseResourceReference[] ReleaseResourceReference {
        get {
            return this.releaseResourceReferenceField;
        }
        set {
            this.releaseResourceReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class NewReleaseMessage {
    
    private string updateIndicatorField;
    
    private string isBackfillField;
    
    private NewReleaseMessageMessageHeader messageHeaderField;
    
    private NewReleaseMessageResourceList resourceListField;
    
    private NewReleaseMessageRelease[] releaseListField;
    
    private string messageSchemaVersionIdField;
    
    private string releaseProfileVersionIdField;
    
    private string languageAndScriptCodeField;
    
    /// <remarks/>
    public string UpdateIndicator {
        get {
            return this.updateIndicatorField;
        }
        set {
            this.updateIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public string IsBackfill {
        get {
            return this.isBackfillField;
        }
        set {
            this.isBackfillField = value;
        }
    }
    
    /// <remarks/>
    public NewReleaseMessageMessageHeader MessageHeader {
        get {
            return this.messageHeaderField;
        }
        set {
            this.messageHeaderField = value;
        }
    }
    
    /// <remarks/>
    public NewReleaseMessageResourceList ResourceList {
        get {
            return this.resourceListField;
        }
        set {
            this.resourceListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Release", IsNullable=false)]
    public NewReleaseMessageRelease[] ReleaseList {
        get {
            return this.releaseListField;
        }
        set {
            this.releaseListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string MessageSchemaVersionId {
        get {
            return this.messageSchemaVersionIdField;
        }
        set {
            this.messageSchemaVersionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string ReleaseProfileVersionId {
        get {
            return this.releaseProfileVersionIdField;
        }
        set {
            this.releaseProfileVersionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string LanguageAndScriptCode {
        get {
            return this.languageAndScriptCodeField;
        }
        set {
            this.languageAndScriptCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageMessageHeader {
    
    private string messageThreadIdField;
    
    private string messageIdField;
    
    private string messageCreatedDateTimeField;
    
    private NewReleaseMessageMessageHeaderMessageSender[] messageSenderField;
    
    private NewReleaseMessageMessageHeaderMessageRecipient[] messageRecipientField;
    
    /// <remarks/>
    public string MessageThreadId {
        get {
            return this.messageThreadIdField;
        }
        set {
            this.messageThreadIdField = value;
        }
    }
    
    /// <remarks/>
    public string MessageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string MessageCreatedDateTime {
        get {
            return this.messageCreatedDateTimeField;
        }
        set {
            this.messageCreatedDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MessageSender")]
    public NewReleaseMessageMessageHeaderMessageSender[] MessageSender {
        get {
            return this.messageSenderField;
        }
        set {
            this.messageSenderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MessageRecipient")]
    public NewReleaseMessageMessageHeaderMessageRecipient[] MessageRecipient {
        get {
            return this.messageRecipientField;
        }
        set {
            this.messageRecipientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageMessageHeaderMessageSender {
    
    private string partyIdField;
    
    /// <remarks/>
    public string PartyId {
        get {
            return this.partyIdField;
        }
        set {
            this.partyIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageMessageHeaderMessageRecipient {
    
    private string partyIdField;
    
    /// <remarks/>
    public string PartyId {
        get {
            return this.partyIdField;
        }
        set {
            this.partyIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceList {
    
    private NewReleaseMessageResourceListSoundRecording[] soundRecordingField;
    
    private NewReleaseMessageResourceListImage[] imageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SoundRecording")]
    public NewReleaseMessageResourceListSoundRecording[] SoundRecording {
        get {
            return this.soundRecordingField;
        }
        set {
            this.soundRecordingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Image")]
    public NewReleaseMessageResourceListImage[] Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListSoundRecording {
    
    private string soundRecordingTypeField;
    
    private string resourceReferenceField;
    
    private string durationField;
    
    private NewReleaseMessageResourceListSoundRecordingSoundRecordingId[] soundRecordingIdField;
    
    private ReferenceTitle[] referenceTitleField;
    
    private NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritory[] soundRecordingDetailsByTerritoryField;
    
    /// <remarks/>
    public string SoundRecordingType {
        get {
            return this.soundRecordingTypeField;
        }
        set {
            this.soundRecordingTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ResourceReference {
        get {
            return this.resourceReferenceField;
        }
        set {
            this.resourceReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SoundRecordingId")]
    public NewReleaseMessageResourceListSoundRecordingSoundRecordingId[] SoundRecordingId {
        get {
            return this.soundRecordingIdField;
        }
        set {
            this.soundRecordingIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReferenceTitle")]
    public ReferenceTitle[] ReferenceTitle {
        get {
            return this.referenceTitleField;
        }
        set {
            this.referenceTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SoundRecordingDetailsByTerritory")]
    public NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritory[] SoundRecordingDetailsByTerritory {
        get {
            return this.soundRecordingDetailsByTerritoryField;
        }
        set {
            this.soundRecordingDetailsByTerritoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListSoundRecordingSoundRecordingId {
    
    private string iSRCField;
    
    /// <remarks/>
    public string ISRC {
        get {
            return this.iSRCField;
        }
        set {
            this.iSRCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritory {
    
    private string territoryCodeField;
    
    private string resourceReleaseDateField;
    
    private string parentalWarningTypeField;
    
    private Title[] titleField;
    
    private DisplayArtist[] displayArtistField;
    
    private NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryResourceContributor[] resourceContributorField;
    
    private NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryIndirectResourceContributor[] indirectResourceContributorField;
    
    private PLine[] pLineField;
    
    private Genre[] genreField;
    
    private NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryTechnicalSoundRecordingDetails[] technicalSoundRecordingDetailsField;
    
    /// <remarks/>
    public string TerritoryCode {
        get {
            return this.territoryCodeField;
        }
        set {
            this.territoryCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ResourceReleaseDate {
        get {
            return this.resourceReleaseDateField;
        }
        set {
            this.resourceReleaseDateField = value;
        }
    }
    
    /// <remarks/>
    public string ParentalWarningType {
        get {
            return this.parentalWarningTypeField;
        }
        set {
            this.parentalWarningTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Title")]
    public Title[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DisplayArtist")]
    public DisplayArtist[] DisplayArtist {
        get {
            return this.displayArtistField;
        }
        set {
            this.displayArtistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResourceContributor")]
    public NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryResourceContributor[] ResourceContributor {
        get {
            return this.resourceContributorField;
        }
        set {
            this.resourceContributorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IndirectResourceContributor")]
    public NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryIndirectResourceContributor[] IndirectResourceContributor {
        get {
            return this.indirectResourceContributorField;
        }
        set {
            this.indirectResourceContributorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PLine")]
    public PLine[] PLine {
        get {
            return this.pLineField;
        }
        set {
            this.pLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Genre")]
    public Genre[] Genre {
        get {
            return this.genreField;
        }
        set {
            this.genreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TechnicalSoundRecordingDetails")]
    public NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryTechnicalSoundRecordingDetails[] TechnicalSoundRecordingDetails {
        get {
            return this.technicalSoundRecordingDetailsField;
        }
        set {
            this.technicalSoundRecordingDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryResourceContributor {
    
    private string resourceContributorRoleField;
    
    private PartyName[] partyNameField;
    
    private string sequenceNumberField;
    
    /// <remarks/>
    public string ResourceContributorRole {
        get {
            return this.resourceContributorRoleField;
        }
        set {
            this.resourceContributorRoleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PartyName")]
    public PartyName[] PartyName {
        get {
            return this.partyNameField;
        }
        set {
            this.partyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryIndirectResourceContributor {
    
    private string indirectResourceContributorRoleField;
    
    private PartyName[] partyNameField;
    
    private string sequenceNumberField;
    
    /// <remarks/>
    public string IndirectResourceContributorRole {
        get {
            return this.indirectResourceContributorRoleField;
        }
        set {
            this.indirectResourceContributorRoleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PartyName")]
    public PartyName[] PartyName {
        get {
            return this.partyNameField;
        }
        set {
            this.partyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string SequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListSoundRecordingSoundRecordingDetailsByTerritoryTechnicalSoundRecordingDetails {
    
    private string technicalResourceDetailsReferenceField;
    
    private File[] fileField;
    
    /// <remarks/>
    public string TechnicalResourceDetailsReference {
        get {
            return this.technicalResourceDetailsReferenceField;
        }
        set {
            this.technicalResourceDetailsReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("File")]
    public File[] File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListImage {
    
    private string imageTypeField;
    
    private string resourceReferenceField;
    
    private NewReleaseMessageResourceListImageImageIdProprietaryId[][] imageIdField;
    
    private NewReleaseMessageResourceListImageImageDetailsByTerritory[] imageDetailsByTerritoryField;
    
    /// <remarks/>
    public string ImageType {
        get {
            return this.imageTypeField;
        }
        set {
            this.imageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ResourceReference {
        get {
            return this.resourceReferenceField;
        }
        set {
            this.resourceReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ProprietaryId", typeof(NewReleaseMessageResourceListImageImageIdProprietaryId))]
    public NewReleaseMessageResourceListImageImageIdProprietaryId[][] ImageId {
        get {
            return this.imageIdField;
        }
        set {
            this.imageIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ImageDetailsByTerritory")]
    public NewReleaseMessageResourceListImageImageDetailsByTerritory[] ImageDetailsByTerritory {
        get {
            return this.imageDetailsByTerritoryField;
        }
        set {
            this.imageDetailsByTerritoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListImageImageIdProprietaryId {
    
    private string namespaceField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string Namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListImageImageDetailsByTerritory {
    
    private string territoryCodeField;
    
    private string parentalWarningTypeField;
    
    private NewReleaseMessageResourceListImageImageDetailsByTerritoryTechnicalImageDetails[] technicalImageDetailsField;
    
    /// <remarks/>
    public string TerritoryCode {
        get {
            return this.territoryCodeField;
        }
        set {
            this.territoryCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ParentalWarningType {
        get {
            return this.parentalWarningTypeField;
        }
        set {
            this.parentalWarningTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TechnicalImageDetails")]
    public NewReleaseMessageResourceListImageImageDetailsByTerritoryTechnicalImageDetails[] TechnicalImageDetails {
        get {
            return this.technicalImageDetailsField;
        }
        set {
            this.technicalImageDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageResourceListImageImageDetailsByTerritoryTechnicalImageDetails {
    
    private string technicalResourceDetailsReferenceField;
    
    private File[] fileField;
    
    /// <remarks/>
    public string TechnicalResourceDetailsReference {
        get {
            return this.technicalResourceDetailsReferenceField;
        }
        set {
            this.technicalResourceDetailsReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("File")]
    public File[] File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageRelease {
    
    private string releaseReferenceField;
    
    private string releaseTypeField;
    
    private NewReleaseMessageReleaseReleaseId[] releaseIdField;
    
    private ReferenceTitle[] referenceTitleField;
    
    private ReleaseResourceReference[][] releaseResourceReferenceListField;
    
    private NewReleaseMessageReleaseReleaseDetailsByTerritory[] releaseDetailsByTerritoryField;
    
    private PLine[] pLineField;
    
    private NewReleaseMessageReleaseCLine[] cLineField;
    
    private NewReleaseMessageReleaseGlobalOriginalReleaseDate[] globalOriginalReleaseDateField;
    
    private string isMainReleaseField;
    
    /// <remarks/>
    public string ReleaseReference {
        get {
            return this.releaseReferenceField;
        }
        set {
            this.releaseReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string ReleaseType {
        get {
            return this.releaseTypeField;
        }
        set {
            this.releaseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReleaseId")]
    public NewReleaseMessageReleaseReleaseId[] ReleaseId {
        get {
            return this.releaseIdField;
        }
        set {
            this.releaseIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReferenceTitle")]
    public ReferenceTitle[] ReferenceTitle {
        get {
            return this.referenceTitleField;
        }
        set {
            this.referenceTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ReleaseResourceReference", typeof(ReleaseResourceReference))]
    public ReleaseResourceReference[][] ReleaseResourceReferenceList {
        get {
            return this.releaseResourceReferenceListField;
        }
        set {
            this.releaseResourceReferenceListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReleaseDetailsByTerritory")]
    public NewReleaseMessageReleaseReleaseDetailsByTerritory[] ReleaseDetailsByTerritory {
        get {
            return this.releaseDetailsByTerritoryField;
        }
        set {
            this.releaseDetailsByTerritoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PLine")]
    public PLine[] PLine {
        get {
            return this.pLineField;
        }
        set {
            this.pLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CLine")]
    public NewReleaseMessageReleaseCLine[] CLine {
        get {
            return this.cLineField;
        }
        set {
            this.cLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GlobalOriginalReleaseDate", IsNullable=true)]
    public NewReleaseMessageReleaseGlobalOriginalReleaseDate[] GlobalOriginalReleaseDate {
        get {
            return this.globalOriginalReleaseDateField;
        }
        set {
            this.globalOriginalReleaseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string IsMainRelease {
        get {
            return this.isMainReleaseField;
        }
        set {
            this.isMainReleaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageReleaseReleaseId {
    
    private string iSRCField;
    
    private NewReleaseMessageReleaseReleaseIdICPN[] iCPNField;
    
    /// <remarks/>
    public string ISRC {
        get {
            return this.iSRCField;
        }
        set {
            this.iSRCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ICPN", IsNullable=true)]
    public NewReleaseMessageReleaseReleaseIdICPN[] ICPN {
        get {
            return this.iCPNField;
        }
        set {
            this.iCPNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageReleaseReleaseIdICPN {
    
    private string isEanField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string IsEan {
        get {
            return this.isEanField;
        }
        set {
            this.isEanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageReleaseReleaseDetailsByTerritory {
    
    private string territoryCodeField;
    
    private string displayArtistNameField;
    
    private string labelNameField;
    
    private string parentalWarningTypeField;
    
    private Title[] titleField;
    
    private DisplayArtist[] displayArtistField;
    
    private ResourceGroup[] resourceGroupField;
    
    private NewReleaseMessageReleaseReleaseDetailsByTerritoryResourceGroupFirst[] resourceGroupFirstField;
    
    private Genre[] genreField;
    
    private NewReleaseMessageReleaseReleaseDetailsByTerritoryReleaseDate[] releaseDateField;
    
    /// <remarks/>
    public string TerritoryCode {
        get {
            return this.territoryCodeField;
        }
        set {
            this.territoryCodeField = value;
        }
    }
    
    /// <remarks/>
    public string DisplayArtistName {
        get {
            return this.displayArtistNameField;
        }
        set {
            this.displayArtistNameField = value;
        }
    }
    
    /// <remarks/>
    public string LabelName {
        get {
            return this.labelNameField;
        }
        set {
            this.labelNameField = value;
        }
    }
    
    /// <remarks/>
    public string ParentalWarningType {
        get {
            return this.parentalWarningTypeField;
        }
        set {
            this.parentalWarningTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Title")]
    public Title[] Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DisplayArtist")]
    public DisplayArtist[] DisplayArtist {
        get {
            return this.displayArtistField;
        }
        set {
            this.displayArtistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResourceGroup")]
    public ResourceGroup[] ResourceGroup {
        get {
            return this.resourceGroupField;
        }
        set {
            this.resourceGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResourceGroupFirst")]
    public NewReleaseMessageReleaseReleaseDetailsByTerritoryResourceGroupFirst[] ResourceGroupFirst {
        get {
            return this.resourceGroupFirstField;
        }
        set {
            this.resourceGroupFirstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Genre")]
    public Genre[] Genre {
        get {
            return this.genreField;
        }
        set {
            this.genreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReleaseDate", IsNullable=true)]
    public NewReleaseMessageReleaseReleaseDetailsByTerritoryReleaseDate[] ReleaseDate {
        get {
            return this.releaseDateField;
        }
        set {
            this.releaseDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageReleaseReleaseDetailsByTerritoryResourceGroupFirst {
    
    private ResourceGroup[] resourceGroupField;
    
    private ResourceGroupContentItem[] resourceGroupContentItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResourceGroup")]
    public ResourceGroup[] ResourceGroup {
        get {
            return this.resourceGroupField;
        }
        set {
            this.resourceGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResourceGroupContentItem")]
    public ResourceGroupContentItem[] ResourceGroupContentItem {
        get {
            return this.resourceGroupContentItemField;
        }
        set {
            this.resourceGroupContentItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageReleaseReleaseDetailsByTerritoryReleaseDate {
    
    private string isApproximateField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string IsApproximate {
        get {
            return this.isApproximateField;
        }
        set {
            this.isApproximateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageReleaseCLine {
    
    private string yearField;
    
    private string cLineTextField;
    
    /// <remarks/>
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public string CLineText {
        get {
            return this.cLineTextField;
        }
        set {
            this.cLineTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
public partial class NewReleaseMessageReleaseGlobalOriginalReleaseDate {
    
    private string isApproximateField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string IsApproximate {
        get {
            return this.isApproximateField;
        }
        set {
            this.isApproximateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ddex.net/xml/ern/382")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://ddex.net/xml/ern/382", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DisplayArtist", typeof(DisplayArtist))]
    [System.Xml.Serialization.XmlElementAttribute("File", typeof(File))]
    [System.Xml.Serialization.XmlElementAttribute("Genre", typeof(Genre))]
    [System.Xml.Serialization.XmlElementAttribute("NewReleaseMessage", typeof(NewReleaseMessage))]
    [System.Xml.Serialization.XmlElementAttribute("PLine", typeof(PLine))]
    [System.Xml.Serialization.XmlElementAttribute("PartyName", typeof(PartyName))]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceTitle", typeof(ReferenceTitle))]
    [System.Xml.Serialization.XmlElementAttribute("ReleaseResourceReference", typeof(ReleaseResourceReference), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("ResourceGroup", typeof(ResourceGroup))]
    [System.Xml.Serialization.XmlElementAttribute("ResourceGroupContentItem", typeof(ResourceGroupContentItem))]
    [System.Xml.Serialization.XmlElementAttribute("Title", typeof(Title))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
